export const Errors = {
  Error: 'Error',
  SERVER_ERROR: 'SERVER_ERROR',
  INCORECT_CREDINTIAL: 'INCORECT_CREDINTIAL',
  NOT_FOUND: 'NOT_FOUND',
  EXISTS: 'EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
};

export const ErrorStatus = {
  SERVER_ERROR: 500,
  INCORECT_CREDINTIAL: 401,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  EXISTS: 409,
};

export const ValidationErrors = {
  REQUIRED: 'REQUIRED',
  NO_UPDATE: 'NO_UPDATE',
};
